env:
  node: true
extends: ['eslint:recommended', "plugin:vue/essential", "prettier"]
parserOptions:
  babel-eslint: 'babel-eslint'
plugins:
  - prettier
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-undef:
    - error  
  browserslist:
    - "> 1%"
    - "last 2 versions"
    - "not ie <= 8"
  